# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -g -Wall

# Target executable for testing
TARGET = testerOutWindows

# Source files
SRC = Topping.cpp Meat.cpp FruitOrVeg.cpp Pepperoni.cpp Chicken.cpp Pineapple.cpp Olive.cpp ToppingTester.cpp

# Build target
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS) $(LIBS)

# Clean target
clean:
	rm -f $(TARGET)